### ISSUE TITLE
Kisi Feedback

### ISSUE THREAD

**Issue by ce07c3** [schnipseljagd/kisi-event-notifications#1]
Hey @schnipseljagd!

Thanks a lot for the submission. Looks solid, I'll try to run the application later during the day.

Just a few quick questions upfront:

- How would you add authentication and authorization logic to the app? Let's say we don't want anyone to be able to post events to the application. Then we'd have to authenticate the sender in some way or another. Stripe has a few ideas on how to do this, do you think they might be a good fit?
- If we wanted to build a "boosted" version of the rules matcher, what architecture/patterns would you choose and why?
- Let's say we didn't wish to use Redis for our jobs backend. What alternatives do we have?
- Do we need to protect the application from CORS attacks given its use cases?

Looking forward to your ideas! :)

Best,

Carl

**Comment by schnipseljagd** [comment]
> How would you add authentication and authorization logic to the app? Let's say we don't want anyone to be able to post events to the application. Then we'd have to authenticate the sender in some way or another. Stripe has a few ideas on how to do this, do you think they might be a good fit?

The simplest thing I would have considered here, is to authenticate the consumer with a shared API key and to use e.g. basic auth to authenticate every HTTP request. 

The stripe idea of signing every request with an hmac of an API key and the request body plus a timestamp comes with some security advantages compared to simple basic auth.
 * It let's us makes sure the request was send by a consumer with the API key.
 * It let's us validate that the request wasn't modified during transit between the consumer and the endpoint.
 * It protects us against potential replay attacks because we can simply check that the timestamp is not older than our accepted time frame.

I would definitely consider it a good fit.
Additionally it may be interesting to mention here that [AWS](https://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html) uses a similar approach for nearly all API requests.
Although they use public/private key pairs for the signature. 


> If we wanted to build a "boosted" version of the rules matcher, what architecture/patterns would you choose and why?

Since I don't know what kind of features and requirements a "boosted" version contains, I can't really make a choice here. I think the current design is pretty open and well tested so it probably could just evolve with it's requirements.
Reasonable seems to me to make the rules and subscribers configurable via an API and maybe also to allow alternative deliveries to emails.
If you want a more specific answer about software design patterns. Maybe you can share some more details here?

> Let's say we didn't wish to use Redis for our jobs backend. What alternatives do we have?

First of all I think it is good to question Redis as a job backend because there has been a lot of discussion and research going on which at leasts questions it's high availability guarantees (see e.g. https://aphyr.com/tags/Redis).
If we don't need an highly available job backend and our workload is in it's limits we could simply go with a [Postgres backend here](https://github.com/QueueClassic/queue_classic). 
Personally I have really good experiences with AWS SQS as an highly available and easy to use job backend.
Google Cloud seem to provide with Pub/Sub a similar feature set.
There are a lot of other interesting alternatives like ZeroMQ which I won't consider here because I think there is no need to run a custom job backend by our own.
I generally prefer to free myself from operational work if there are good hosted solutions.

> Do we need to protect the application from CORS attacks given its use cases?

I won't say so since there is no client-side web application involved in the communication between the Kisi webhook API and and the event-notification service.

**Comment by ce07c3** [comment]
@schnipseljagd makes a lot of sense!

I'll continue our conversation via email. :)
